name: Publish
run-name: "Building & publishing ${{ github.ref_name }}"

on:
  workflow_dispatch: { }
  push:
    branches:
      - "!*"
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: |
          version="$(echo '${{ github.ref_name }}' | sed 's/^v//')"
          mvn -B package "-Dteamcity.ugsStatusPublisher.plugin.version=$version"
      - uses: actions/upload-artifact@v3
        with:
          path: target/ugsStatusPublisher.zip